CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY,
	username VARCHAR(25) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	permission VARCHAR(20) NOT NULL,
	photo_path VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS planets (
	id INTEGER PRIMARY KEY,
	name VARCHAR(25) NOT NULL,
    region VARCHAR(255) NOT NULL,
	sector VARCHAR(255) NOT NULL,
	system VARCHAR(255) NOT NULL,
	inhabitant VARCHAR(255) NOT NULL,
	city VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS stormtroopers (
	id INTEGER PRIMARY KEY,
	name VARCHAR(25) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS destruction (
	id INTEGER PRIMARY KEY,
	planet_id INTEGER NOT NULL UNIQUE,
	date TEXT NOT NULL,
    status INTEGER NOT NULL DEFAULT 0,
	description TEXT NULL
);

